#! /bin/sh

sxhkd &
nitrogen --restore &
#bash ~/.config/polybar/launch.sh --shapes
bash ~/.config/polybar/pinky/launch.sh
nvidia-settings --load-config-only
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         3 
bspc config window_gap           15  

bspc config split_ratio          0.52 
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "##D23D3D"
bspc config focused_border_color "#f3599f"      
bspc config presel_feedback_color "#FF9100"

bspc rule -a Lutris desktop='^3' state=tiled
bspc rule -a OBS desktop='^3' state=tiled
bspc rule -a Steam desktop='^4' state=tiled 
bspc rule -a Firefox desktop='^1' state=tiled follow=on
bspc rule -a VirtualMachineManager desktop='^5' state=tiled follow=on
bspc rule -a Brave desktop='^7' state=tiled follow=on
bspc rule -a DavinciResolve desktop='^6' state=tiled follow=on

xsetroot -cursor_name left_ptr &
dunst &
picom -b --experimental-backends &
nitrogen --restore &
setxkbmap us &
#setxkbmap -option grp:alt_tab_toggle us,tr,fr,de &
$HOME/.mousescript.sh
$HOME/.autostart/com.leinardi.gwe.sh
exec /usr/bin/lxpolkit
exec xrandr --output DP-0 --mode 1920x1080 --rate 240

