#!/bin/sh

sxhkd &
#bash ~/.config/polybar/tokyo/launch.sh
bash ~/.config/polybar/midnight/launch.sh
nvidia-settings --load-config-only
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         3 
bspc config window_gap           10  

bspc config split_ratio          0.52 
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "##D23D3D"
bspc config focused_border_color "#b294bb"      
bspc config presel_feedback_color "#FF9100"

bspc rule -a Lutris desktop='^4' state=tiled
bspc rule -a obs desktop='^5' state=tiled
bspc rule -a Steam desktop='^4' state=tiled 
bspc rule -a Firefox desktop='^1' state=tiled follow=on
bspc rule -a virt-manager desktop='^6' state=tiled
bspc rule -a Brave-browser desktop='^1' state=tiled follow=on

xsetroot -cursor_name left_ptr &
dunst &
picom -b --experimental-backends 
xwallpaper --zoom ~/Pictures/wallpapers-dotfiles/anime-landscapes/Q23.png 
setxkbmap us &
exec gwe --hide-window &
exec xrandr --output DP-0 --mode 1920x1080 --rate 240
exec /usr/bin/lxpolkit
